services:
  - type: web
    name: bosele-kgotla
    env: static
    buildCommand: npm run build
    staticPublishPath: ./out
    routes:
      - type: rewrite
        source: /*
        destination: /index.html